/**
 *
 * CobaltPluginManager
 * Cobalt
 *
 * The MIT License (MIT)
 *
 * Copyright (c) 2014 Cobaltians
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

package fr.cobaltians.cobalt.plugin;

import fr.cobaltians.cobalt.Cobalt;
import fr.cobaltians.cobalt.fragments.CobaltFragment;
import fr.cobaltians.cobalt.plugin.CobaltAbstractPlugin;

import android.app.Activity;
import android.content.Context;
import android.util.Log;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;

import org.json.JSONException;
import org.json.JSONObject;

// Generated by script: imports
import fr.cobaltians.cobalt.plugin.CobaltLocationPlugin;

public class CobaltPluginManager {

	// TAG
	private static final String TAG = CobaltPluginManager.class.getSimpleName();
	
	/********************************************************************************
     * MEMBERS
     ********************************************************************************/
	
	private Context mContext;
	private final HashMap<String, Class<? extends CobaltAbstractPlugin>> mPluginsMap;
	
	/******************************************************************************
     * CONSTRUCTORS
     ******************************************************************************/
	
	public CobaltPluginManager(Context context) {
		mContext = context;
		mPluginsMap = new HashMap<String, Class<? extends CobaltAbstractPlugin>>();
		
		// Generated by script: mPluginsMap populate
		mPluginsMap.put("geoloc", CobaltLocationPlugin.class);
	}
	
	/***********************************************************************************************************************************************************************************
     * COBALT METHODS
     ***********************************************************************************************************************************************************************************/
	
	public boolean onMessage(CobaltFragment fragment, JSONObject message) {
		try {
			String pluginName = message.getString(Cobalt.kJSPluginName);
			Class<? extends CobaltAbstractPlugin> pluginClass = mPluginsMap.get(pluginName);
			if (pluginClass != null) {
				try {
					Constructor<? extends CobaltAbstractPlugin> pluginConstructor = pluginClass.getDeclaredConstructor(Activity.class, CobaltFragment.class, CobaltPluginManager.class);
					try {
						CobaltAbstractPlugin plugin = pluginConstructor.newInstance((Activity) mContext, fragment, this);
						plugin.onMessage(message);
						return true;
					} 
					catch (InstantiationException exception) {
						if (Cobalt.DEBUG) exception.printStackTrace();
					} 
					catch (IllegalAccessException exception) {
						if (Cobalt.DEBUG) exception.printStackTrace();
					} 
					catch (IllegalArgumentException exception) {
						if (Cobalt.DEBUG) exception.printStackTrace();
					} 
					catch (InvocationTargetException exception) {
						if (Cobalt.DEBUG) exception.printStackTrace();
					}
				} 
				catch (NoSuchMethodException exception) {
					if (Cobalt.DEBUG) {
						Log.e(TAG, "onMessage: no constructor found matching public " + pluginClass.getSimpleName() + "(Activity, CobaltFragment, CobaltPluginManager)");
						exception.printStackTrace();
					}
				}
			}
			else if (Cobalt.DEBUG) Log.e(TAG, "onMessage: no plugin class found for name " + pluginName + ".");
		}
		catch(JSONException exception) {
			if (Cobalt.DEBUG) {
				Log.e(TAG, "onMessage: name field not found or not a String.");
				exception.printStackTrace();
			}
		}
		
		return false;
	}
}
